//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_ChangeSchedulefiling
    {
        public long ID { get; set; }
        public string CS_RefNo { get; set; }
        public string BIPH_Agency { get; set; }
        public int FileType { get; set; }
        public string CSType { get; set; }
        public Nullable<long> Schedule { get; set; }
        public string Section { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<long> Line_Team { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string CSin { get; set; }
        public string CSout { get; set; }
        public string Reason { get; set; }
        public int Status { get; set; }
        public int StatusMax { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
