//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_OTfiling_Cumulative
    {
        public long ID { get; set; }
        public string OT_RefNo { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<long> Schedule { get; set; }
        public string ShiftIn { get; set; }
        public string ShiftOut { get; set; }
        public string OTIn { get; set; }
        public string OTOut { get; set; }
        public decimal OTHours { get; set; }
        public System.DateTime OTDate { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
