//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Agency_Email
    {
        public long ID { get; set; }
        public string AgencyCode { get; set; }
        public string EmailAddress { get; set; }
        public string CreateID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
