//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Cost_Center_List
    {
        public long ID { get; set; }
        public string Cost_Center { get; set; }
        public string Section { get; set; }
        public string GroupSection { get; set; }
        public string DepartmentGroup { get; set; }
    }
}
