//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee_CostCenter
    {
        public long ID { get; set; }
        public string EmployNo { get; set; }
        public string CostCenter_AMS { get; set; }
        public string CostCenter_IT { get; set; }
        public string CostCenter_EXPROD { get; set; }
        public Nullable<System.DateTime> UpdateDate_AMS { get; set; }
        public Nullable<System.DateTime> UpdateDate_IT { get; set; }
        public Nullable<System.DateTime> UpdateDate_EXPROD { get; set; }
        public string Update_ID { get; set; }
    }
}
