//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee_Master_List_Schedule
    {
        public long ID { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public Nullable<long> ScheduleID_CSTemp { get; set; }
        public string CSRefNo { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
