//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee_Status
    {
        public long ID { get; set; }
        public string EmployNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Update_ID { get; set; }
        public string HRStatus { get; set; }
        public Nullable<System.DateTime> HRUpdateDate { get; set; }
        public string DateResigned { get; set; }
    }
}
