//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_AttendanceMonitoring
    {
        public long ID { get; set; }
        public string EmployeeNo { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateID { get; set; }
    }
}
