//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TimeTap
    {
        public long ID { get; set; }
        public string Employee_RFID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Tap { get; set; }
        public string Taptype { get; set; }
        public string EmpNo { get; set; }
    }
}
