//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TimeInOut
    {
        public long ID { get; set; }
        public string Employee_RFID { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public long LineID { get; set; }
        public long ProcessID { get; set; }
        public Nullable<System.DateTime> DTR_TimeIn { get; set; }
        public Nullable<System.DateTime> DTR_TimeOut { get; set; }
        public string DTR_RefNo { get; set; }
        public string CSRef_No { get; set; }
        public Nullable<long> CS_ScheduleID { get; set; }
        public string EmployeeRemover { get; set; }
        public string EmpNo { get; set; }
    }
}
