//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brothers_WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_UploadTracker
    {
        public long ID { get; set; }
        public string UploadFile { get; set; }
        public string Uploader { get; set; }
        public Nullable<System.DateTime> Uploaddate { get; set; }
    }
}
